language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

install: true

script: mvn -e clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
